### ISSUE TITLE
Incorrect sent bytes calculation

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_robothub#66]
Line 300 of Robothub.cpp reads 
"    this->statistics.feedbackBytesSent += static_cast<int>(sizeof(feedback));" 
However, since the type of feedback is "RobotsFeedback", which has a vector of RobotFeedbacks, this is not accurately measuring the number of bytes sent as sizeof(std::vector<T>) == 3 * sizeof(T*), regardless of the vectors length/contained entries. It currently thus is not counting the number of bytes in the messages sent correctly as sizeof(RobotsFeedback) is a constant.

**Comment by Florisheinen1** [comment]
Should be fixed with [this PR](https://github.com/RoboTeamTwente/roboteam_robothub/pull/67)
